name: Tests and Allure reports 

on: 
    push:
        branches:
            [ "main" ]
    workflow_dispatch:
      
jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4
      
      - name: Download python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: download dependencies
        run: pip install -r requirements.txt
    
      - name: Install Chrome
        run: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      - name: Run tests
        run: pytest --alluredir=allure-results 

      - name: Generate Allure report
        if: always()
        uses: allure-framework/allure-action@v0 
        with: 
            report-directory: "allure-results"


      - name: Github Actions Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: allure-report
            path: allure-results
        continue-on-error: true 